"""Deterministic trading configuration constants for ORACLE."""

# --- CORE RISK CONSTANTS (requested baseline) ---
STARTING_BALANCE = 100.0
MAX_RISK_PER_TRADE_PCT = 0.02
MAX_DAILY_LOSS_PCT = 0.10
SURVIVAL_THRESHOLD_USDC = 5.00
MIN_NET_EDGE = 0.15

# --- EXECUTION MODE ---
LIVE_TRADING = False
PAPER_TRADING = not LIVE_TRADING

# --- EXECUTION COSTS ---
TAKER_FEE_RATE = 0.0315
MAKER_FEE_RATE = 0.00
SLIPPAGE_BUFFER_PCT = 0.005

# --- OPERATIONAL LIMITS ---
MAX_OPEN_POSITIONS = 3
MAX_TRADES_PER_DAY = 15
MAX_PENDING_LIMIT_ORDERS = 50

# --- OPTIONAL CAPS ---
MIN_POSITION_USDC = 1.00
MAX_POSITION_USDC = 5.00
